function getTime(){
    let d=new Date();

    return (
        d.getDate().toString().padStart(2,'0')+"/"+
        (d.getMonth()+1).toString().padStart(2,'0')+"/"+
        d.getFullYear()+" "+
        d.getHours().toString().padStart(2,'0')+":"+
        d.getMinutes().toString().padStart(2,'0')+":"+
        d.getSeconds().toString().padStart(2,'0')
    );
}

function randName(len){

    let c="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    let o="";

    for(let i=0;i<len;i++){
        o+=c[Math.floor(Math.random()*c.length)];
    }

    return o;
}

function rand(min,max){
    return Math.floor(Math.random()*(max-min+1))+min;
}

function spamLines(){

    let c="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    let o="";

    for(let i=0;i<50;i++){
        o+="\n-- "+c[rand(0,c.length-1)].repeat(rand(3,20));
    }

    return o;
}

function splitRandom(str){

    let a=[];
    let i=0;

    while(i<str.length){

        let s=rand(2,6);

        a.push(str.substring(i,i+s));

        i+=s;
    }

    return a;
}

function xorEncode(str,key){

    let o=[];

    for(let i=0;i<str.length;i++){

        o.push(
            String.fromCharCode(
                str.charCodeAt(i)^key
            )
        );
    }

    return o.join("");
}

function b64(bytes){

    const c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    let o="";
    let i=0;

    while(i<bytes.length){

        let c1=bytes.charCodeAt(i++)&255;
        let c2=bytes.charCodeAt(i++);
        let c3=bytes.charCodeAt(i++);

        let e1=c1>>2;
        let e2=((c1&3)<<4)|(c2>>4);
        let e3=((c2&15)<<2)|(c3>>6);
        let e4=c3&63;

        if(isNaN(c2)){
            e3=e4=64;
        }
        else if(isNaN(c3)){
            e4=64;
        }

        o+=
            c.charAt(e1)+
            c.charAt(e2)+
            (e3!=64?c.charAt(e3):'=')+
            (e4!=64?c.charAt(e4):'=');
    }

    return o;
}

function colorChar(ch){

    const yellow="_=×*:+()[]\"";

    if(/[a-zA-Z]/.test(ch)){
        return `<span style="color:#ff4d4d">${ch}</span>`;
    }

    if(/[0-9]/.test(ch)){
        return `<span style="color:#4dff88">${ch}</span>`;
    }

    if(yellow.includes(ch)){
        return `<span style="color:#ffd84d">${ch}</span>`;
    }

    return `<span style="color:#e6e6e6">${ch}</span>`;
}

function render(text){

    let o="";

    for(let i=0;i<text.length;i++){
        o+=colorChar(text[i]);
    }

    document.getElementById("output").innerHTML=o;
}

function obfuscate(){

    let raw=document.getElementById("input").value;

    if(!raw.trim()){
        return alert("Paste script first");
    }

    let time=getTime();

    raw=
        "-- OBF ACTIVATED: "+time+
        "\n-- GENERATED BY MODZ\n\n"+
        raw;

    raw=raw
        .replace(/\r/g,"")
        .replace(/\nreturn/g,"\n\n\nreturn");

    raw+=spamLines();

    let f1=rand(10,80);
    let f2=rand(10,80);

    let key=((f1*2)+f2)-f1;

    let enc=b64(
        xorEncode(raw,key)
    );

    let chunks=splitRandom(enc);

    let table=[];
    let order=[];

    for(let i=0;i<chunks.length;i++){

        let id=rand(1000,9999);

        table.push(
            `[${id}]="${chunks[i]}"`
        );

        order.push(id);
    }

    table.sort(()=>Math.random()-0.5);

    let a=randName(8);
    let b=randName(8);
    let c=randName(8);
    let d=randName(8);
    let e=randName(8);

    let lua=

"-- OBF ACTIVATED: "+time+"\n"+
"-- MODZ ENGINE FIXED\n\n"+

"local "+a+"={\n"+
table.join(",\n")+
"\n}\n\n"+

"local "+b+"={"+
order.join(",")+
"}\n\n"+

"local function "+c+"()\n"+
" local x=\"\"\n"+
" for _,v in ipairs("+b+") do\n"+
"  x=x.."+a+"[v]\n"+
" end\n"+
" return x\n"+
"end\n\n"+

"local function "+d+"(data)\n"+
" local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'\n"+
" data=string.gsub(data,'[^'..b..'=]','')\n"+
" return (data:gsub('.',function(x)\n"+
"  if(x=='=')then return'' end\n"+
"  local r,f='',(b:find(x)-1)\n"+
"  for i=6,1,-1 do\n"+
"   r=r..((f%2^i-f%2^(i-1)>0)and'1'or'0')\n"+
"  end\n"+
"  return r\n"+
" end):gsub('%d%d%d?%d?%d?%d?%d?%d?',function(x)\n"+
"  if(#x~=8)then return'' end\n"+
"  local c=0\n"+
"  for i=1,8 do\n"+
"   c=c+((x:sub(i,i)=='1')and 2^(8-i)or 0)\n"+
"  end\n"+
"  return string.char(c)\n"+
" end))\n"+
"end\n\n"+

"local function "+e+"(str,key)\n"+
" local o={}\n"+
" for i=1,#str do\n"+
"  o[i]=string.char(bit32.bxor(string.byte(str,i),key))\n"+
" end\n"+
" return table.concat(o)\n"+
"end\n\n"+

"local decoded="+e+"("+d+"("+c+"()),"+key+")\n"+
"local fn=(loadstring or load)(decoded)\n"+
"return fn()\n";

    render(lua);
}

function copyOut(){

    navigator.clipboard.writeText(
        document.getElementById("output").innerText
    );
}

function clearAll(){

    document.getElementById("input").value="";

    document.getElementById("output").innerHTML="";
                        }
